version: '3'
services:
  sidecar:
    image: nginx:latest
    volumes:
      - /etc/hosts:/etc/hosts

    ports:
      - 2567:80

    tty: true
    restart: on-failure

  initcontainer:
    image: redis
    volumes:
      - /etc/hosts:/etc/hosts

    ports:
      - 2567:6379

    tty: true
    restart: on-failure

